title: "Cathryn P. Murphy"
description: "Academic Profile & Research"
url: "https://cathrynpmurphy.github.io"
baseurl: ""
author:
  name: "Cathryn P. Murphy"

# Remote theme compatible with GitHub Pages
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

#Head Scripts
head_scripts:
  - /assets/css/custom.css

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jemoji
  - jekyll-remote-theme
  - jekyll-include-cache 

# Theme settings
minimal_mistakes_skin: "air"

# Site settings
locale: "en-US"
repository: "cathrynpmurphy/cathrynpmurphy.github.io"

#Author Page
author:
  name: "Cathryn (Kate) P. Murphy"
  avatar: "/assets/images/SailboatPhoto.jpeg"  # your photo
  bio: "Hi! I'm Kate, a PhD student working on stochastic thermodynamics and thermodynamic computing. My expected graduation is September of 2027."
  links:
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=FIQ_jgIAAAAJ&hl=en"
    - label: "CV"
      icon: "fas fa-fw fa-file-pdf"
      url: "https://cathrynpmurphy.github.io/assets/files/CV_Cathryn_Murphy_Full.pdf"
    - label: "CathrynMurphy2027@u.northwestern.edu"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:CathrynMurphy2027@u.northwestern.edu"
    

# Navigation
header_pages:
  - about.md
  - research.md
  - cv.md
  - interests.md

# Pagination
paginate: 5
paginate_path: /page:num/

# Markdown
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - .github
  - Gemfile
  - Gemfile.lock
  - node_modules
